swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: Simple Inventory API
  # put the contact info for your development or API team
  contact:
    email: you@your-company.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers

paths:
  /book:
    get:
      tags:
      - developers
      summary: search books
      operationId: searchBook
      description: |
        By passing in the appropriate options, you can search for
        available book in the system
      produces:
      - application/json
      parameters:
      - in: query
        name: searchBook
        description: pass an optional search string for looking up book
        required: false
        type: string
      - in: query
        name: author
        description: pass an optional search string for looking up author
        required: false
        type: string
      - in: query
        name: publisher
        description: pass an optional search string for looking up publisher
        required: false
        type: string
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/BooksItem'
        400:
          description: bad input parameter
    post:
      tags:
      - admins
      summary: adds an book item
      operationId: addBook
      description: Adds an item to the system
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: BookItem
        description: Inventory item to add
        schema:
          $ref: '#/definitions/BooksItem'
      responses:
        201:
          description: item created
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists
definitions:
  BooksItem:
    type: object
    required:
    - id
    - title
    - author
    - publisher
    - create_at
    - update_at
    properties:
      id:
        type: integer
        format: uuid
        example: 1
      title:
        type: string
        example: java itu mudah
      author:
        type: string
        example: wawan
      publisher:
        type: string
        example: gramedia
      create_at:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
      update_at:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /wan_team/pesan_buku/1.0.0
schemes:
 - https