// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	transactions "alterra/business/transactions"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetById provides a mock function with given fields: ctx, id
func (_m *Repository) GetById(ctx context.Context, id uint) (transactions.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 transactions.Domain
	if rf, ok := ret.Get(0).(func(context.Context, uint) transactions.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(transactions.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListTransactions provides a mock function with given fields: ctx, Method_Payment_Id, User_Id, Karyawan_Id
func (_m *Repository) GetListTransactions(ctx context.Context, Method_Payment_Id uint, User_Id uint, Karyawan_Id uint) ([]transactions.Domain, error) {
	ret := _m.Called(ctx, Method_Payment_Id, User_Id, Karyawan_Id)

	var r0 []transactions.Domain
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, uint) []transactions.Domain); ok {
		r0 = rf(ctx, Method_Payment_Id, User_Id, Karyawan_Id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transactions.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, uint) error); ok {
		r1 = rf(ctx, Method_Payment_Id, User_Id, Karyawan_Id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertTransactions provides a mock function with given fields: ctx, domain
func (_m *Repository) InsertTransactions(ctx context.Context, domain *transactions.Domain) (transactions.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 transactions.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *transactions.Domain) transactions.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(transactions.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *transactions.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, domain, id
func (_m *Repository) Update(ctx context.Context, domain transactions.Domain, id uint) (transactions.Domain, error) {
	ret := _m.Called(ctx, domain, id)

	var r0 transactions.Domain
	if rf, ok := ret.Get(0).(func(context.Context, transactions.Domain, uint) transactions.Domain); ok {
		r0 = rf(ctx, domain, id)
	} else {
		r0 = ret.Get(0).(transactions.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, transactions.Domain, uint) error); ok {
		r1 = rf(ctx, domain, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
