// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	transaction_details "alterra/business/transaction_details"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Usecase) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetById provides a mock function with given fields: ctx, id
func (_m *Usecase) GetById(ctx context.Context, id uint) (transaction_details.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 transaction_details.Domain
	if rf, ok := ret.Get(0).(func(context.Context, uint) transaction_details.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(transaction_details.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListTransaction_Details provides a mock function with given fields: ctx, search
func (_m *Usecase) GetListTransaction_Details(ctx context.Context, search string) ([]transaction_details.Domain, error) {
	ret := _m.Called(ctx, search)

	var r0 []transaction_details.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) []transaction_details.Domain); ok {
		r0 = rf(ctx, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transaction_details.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertTransaction_Details provides a mock function with given fields: ctx, domain
func (_m *Usecase) InsertTransaction_Details(ctx context.Context, domain transaction_details.Domain) (transaction_details.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 transaction_details.Domain
	if rf, ok := ret.Get(0).(func(context.Context, transaction_details.Domain) transaction_details.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(transaction_details.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, transaction_details.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, domain, id
func (_m *Usecase) Update(ctx context.Context, domain transaction_details.Domain, id uint) (transaction_details.Domain, error) {
	ret := _m.Called(ctx, domain, id)

	var r0 transaction_details.Domain
	if rf, ok := ret.Get(0).(func(context.Context, transaction_details.Domain, uint) transaction_details.Domain); ok {
		r0 = rf(ctx, domain, id)
	} else {
		r0 = ret.Get(0).(transaction_details.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, transaction_details.Domain, uint) error); ok {
		r1 = rf(ctx, domain, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
