// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	karyawans "alterra/business/karyawans"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *Repository) GetAll(ctx context.Context) ([]karyawans.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []karyawans.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []karyawans.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]karyawans.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *Repository) GetByEmail(ctx context.Context, email string) (karyawans.Domain, error) {
	ret := _m.Called(ctx, email)

	var r0 karyawans.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) karyawans.Domain); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(karyawans.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *Repository) GetById(ctx context.Context, id uint) (karyawans.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 karyawans.Domain
	if rf, ok := ret.Get(0).(func(context.Context, uint) karyawans.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(karyawans.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, domain
func (_m *Repository) Register(ctx context.Context, domain *karyawans.Domain) (karyawans.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 karyawans.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *karyawans.Domain) karyawans.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(karyawans.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *karyawans.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, domain, id
func (_m *Repository) Update(ctx context.Context, domain karyawans.Domain, id uint) (karyawans.Domain, error) {
	ret := _m.Called(ctx, domain, id)

	var r0 karyawans.Domain
	if rf, ok := ret.Get(0).(func(context.Context, karyawans.Domain, uint) karyawans.Domain); ok {
		r0 = rf(ctx, domain, id)
	} else {
		r0 = ret.Get(0).(karyawans.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, karyawans.Domain, uint) error); ok {
		r1 = rf(ctx, domain, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
