// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	karyawans "alterra/business/karyawans"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Usecase) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *Usecase) GetAll(ctx context.Context) ([]karyawans.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []karyawans.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []karyawans.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]karyawans.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *Usecase) GetById(ctx context.Context, id uint) (karyawans.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 karyawans.Domain
	if rf, ok := ret.Get(0).(func(context.Context, uint) karyawans.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(karyawans.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *Usecase) Login(ctx context.Context, email string, password string) (karyawans.Domain, string, error) {
	ret := _m.Called(ctx, email, password)

	var r0 karyawans.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string, string) karyawans.Domain); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(karyawans.Domain)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Register provides a mock function with given fields: ctx, domain
func (_m *Usecase) Register(ctx context.Context, domain karyawans.Domain) (karyawans.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 karyawans.Domain
	if rf, ok := ret.Get(0).(func(context.Context, karyawans.Domain) karyawans.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(karyawans.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, karyawans.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, domain, id
func (_m *Usecase) Update(ctx context.Context, domain karyawans.Domain, id uint) (karyawans.Domain, error) {
	ret := _m.Called(ctx, domain, id)

	var r0 karyawans.Domain
	if rf, ok := ret.Get(0).(func(context.Context, karyawans.Domain, uint) karyawans.Domain); ok {
		r0 = rf(ctx, domain, id)
	} else {
		r0 = ret.Get(0).(karyawans.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, karyawans.Domain, uint) error); ok {
		r1 = rf(ctx, domain, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
