// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	wishlists "alterra/business/wishlists"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Usecase) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetById provides a mock function with given fields: ctx, id
func (_m *Usecase) GetById(ctx context.Context, id uint) (wishlists.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 wishlists.Domain
	if rf, ok := ret.Get(0).(func(context.Context, uint) wishlists.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(wishlists.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListWishlist provides a mock function with given fields: ctx, User_Id, Book_Id
func (_m *Usecase) GetListWishlist(ctx context.Context, User_Id uint, Book_Id uint) ([]wishlists.Domain, error) {
	ret := _m.Called(ctx, User_Id, Book_Id)

	var r0 []wishlists.Domain
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) []wishlists.Domain); ok {
		r0 = rf(ctx, User_Id, Book_Id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]wishlists.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, User_Id, Book_Id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertWishlist provides a mock function with given fields: ctx, domain
func (_m *Usecase) InsertWishlist(ctx context.Context, domain *wishlists.Domain) (wishlists.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 wishlists.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *wishlists.Domain) wishlists.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(wishlists.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *wishlists.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, domain, id
func (_m *Usecase) Update(ctx context.Context, domain wishlists.Domain, id uint) (wishlists.Domain, error) {
	ret := _m.Called(ctx, domain, id)

	var r0 wishlists.Domain
	if rf, ok := ret.Get(0).(func(context.Context, wishlists.Domain, uint) wishlists.Domain); ok {
		r0 = rf(ctx, domain, id)
	} else {
		r0 = ret.Get(0).(wishlists.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, wishlists.Domain, uint) error); ok {
		r1 = rf(ctx, domain, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
